### ISSUE TITLE
Grafana integration (useful logging of resource usage/deletion)

### ISSUE THREAD

**Issue by erlend-0** [nais/babylon#21] opened 2021-07-16 08:53 UTC
### Potential metrics 
- No. would-be-pruned resources 
- No. alerts sent with different time intervals
- No. failing resources sorted by reason for failing
- No. of teams affected
- No. deployments currently in Pending or Failing, and their error messages 

- [x] Add rule activations to controller metrics

**Comment by henrikhorluck** [comment] 2021-07-16 08:54
Duplicate of https://github.com/nais/babylon/projects/1#card-64377607?

**Closed as completed** 2021-07-30 07:55 UTC
